const swaggerAutogen    = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5050",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {},
    definitions: {},
    components: {}
};

const outputFile        = './swagger.json';
const endpointsFiles    = ['./routes.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);